name: jackedlog
description: Track gym progress, visualize graphs, enjoy offline support & timers
publish_to: none
version: 1.1.0+1
environment:
  sdk: ">=3.2.6 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  drift: ^2.28.1
  sqlite3_flutter_libs: ^0.5.39
  path_provider: ^2.1.2
  path: ^1.8.3
  csv: ^6.0.0
  intl: ^0.20.2
  fl_chart: ^1.0.0
  permission_handler: ^12.0.1
  provider: ^6.1.1
  dynamic_color: ^1.7.0
  sqlite3: ^2.4.0
  file_picker: ^10.2.0
  image_picker: ^1.0.7
  share_plus: ^11.0.0
  spotify_sdk: ^3.0.0
  audioplayers: ^6.5.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.6
  badges: ^3.1.2
  flutter_local_notifications: ^19.3.0
  timeago: ^3.2.2
  archive: ^4.0.0
  rive: ^0.13.18
  palette_generator: ^0.3.3
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  drift_dev: ^2.28.1
  build_runner: ^2.6.0
  flutter_launcher_icons: ^0.14.2
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "screenshots/app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "screenshots/app_icon.png"
