name: jackedlog_server
description: JackedLog backup server - receives and manages SQLite backup files
version: 1.0.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  sqlite3: ^3.1.5
  shelf_multipart: ^2.0.1
